/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated.certificates'
import { Route as AuthenticatedFilesRouteImport } from './routes/_authenticated.files'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated.integrations'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated.overview'
import { Route as AuthenticatedTerminalRouteImport } from './routes/_authenticated.terminal'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated.services.index'
import { Route as AuthenticatedServicesNginxRouteImport } from './routes/_authenticated.services.nginx'
import { Route as AuthenticatedSessionReauthRouteImport } from './routes/_authenticated.session.reauth'
import { Route as AuthenticatedSettingsAccessRouteImport } from './routes/_authenticated.settings.access'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFilesRoute = AuthenticatedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTerminalRoute = AuthenticatedTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesNginxRoute =
  AuthenticatedServicesNginxRouteImport.update({
    id: '/services/nginx',
    path: '/services/nginx',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionReauthRoute =
  AuthenticatedSessionReauthRouteImport.update({
    id: '/session/reauth',
    path: '/session/reauth',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAccessRoute =
  AuthenticatedSettingsAccessRouteImport.update({
    id: '/settings/access',
    path: '/settings/access',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/files': typeof AuthenticatedFilesRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/terminal': typeof AuthenticatedTerminalRoute
  '/services/nginx': typeof AuthenticatedServicesNginxRoute
  '/session/reauth': typeof AuthenticatedSessionReauthRoute
  '/settings/access': typeof AuthenticatedSettingsAccessRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/files': typeof AuthenticatedFilesRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/terminal': typeof AuthenticatedTerminalRoute
  '/services/nginx': typeof AuthenticatedServicesNginxRoute
  '/session/reauth': typeof AuthenticatedSessionReauthRoute
  '/settings/access': typeof AuthenticatedSettingsAccessRoute
  '/services': typeof AuthenticatedServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/files': typeof AuthenticatedFilesRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/terminal': typeof AuthenticatedTerminalRoute
  '/_authenticated/services/nginx': typeof AuthenticatedServicesNginxRoute
  '/_authenticated/session/reauth': typeof AuthenticatedSessionReauthRoute
  '/_authenticated/settings/access': typeof AuthenticatedSettingsAccessRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/certificates'
    | '/files'
    | '/integrations'
    | '/overview'
    | '/terminal'
    | '/services/nginx'
    | '/session/reauth'
    | '/settings/access'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/certificates'
    | '/files'
    | '/integrations'
    | '/overview'
    | '/terminal'
    | '/services/nginx'
    | '/session/reauth'
    | '/settings/access'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/certificates'
    | '/_authenticated/files'
    | '/_authenticated/integrations'
    | '/_authenticated/overview'
    | '/_authenticated/terminal'
    | '/_authenticated/services/nginx'
    | '/_authenticated/session/reauth'
    | '/_authenticated/settings/access'
    | '/_authenticated/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/files': {
      id: '/_authenticated/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthenticatedFilesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/terminal': {
      id: '/_authenticated/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof AuthenticatedTerminalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/nginx': {
      id: '/_authenticated/services/nginx'
      path: '/services/nginx'
      fullPath: '/services/nginx'
      preLoaderRoute: typeof AuthenticatedServicesNginxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/session/reauth': {
      id: '/_authenticated/session/reauth'
      path: '/session/reauth'
      fullPath: '/session/reauth'
      preLoaderRoute: typeof AuthenticatedSessionReauthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/access': {
      id: '/_authenticated/settings/access'
      path: '/settings/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof AuthenticatedSettingsAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedFilesRoute: typeof AuthenticatedFilesRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedTerminalRoute: typeof AuthenticatedTerminalRoute
  AuthenticatedServicesNginxRoute: typeof AuthenticatedServicesNginxRoute
  AuthenticatedSessionReauthRoute: typeof AuthenticatedSessionReauthRoute
  AuthenticatedSettingsAccessRoute: typeof AuthenticatedSettingsAccessRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedFilesRoute: AuthenticatedFilesRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedTerminalRoute: AuthenticatedTerminalRoute,
  AuthenticatedServicesNginxRoute: AuthenticatedServicesNginxRoute,
  AuthenticatedSessionReauthRoute: AuthenticatedSessionReauthRoute,
  AuthenticatedSettingsAccessRoute: AuthenticatedSettingsAccessRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
