d /run/jw-agent 0750 root jw-agent -
d /run/jw-agent-proxy 2750 jw-agent jw-agent-proxy -
d /var/lib/jw-agent 0750 root jw-agent -
d /var/lib/jw-agent/agentd 0700 jw-agent jw-agent -
d /var/lib/jw-agent/opsd 0700 root root -
d /var/lib/jw-agent/opsd/snapshots 0700 root root -
